### ISSUE TITLE
How do I get the apiKey, reqUrl and pullUrl ?

### ISSUE THREAD

**Issue by Edduard** [peterszombati/metatrader4#3]
I'm trying to make a nodeJS server communicate with MT4 and make transactions from the server. I'm using metatrader4 with teletrade.eu as a broker. Now where do I get the API key and other details? 

I tried to use https://www.metatrader4.com/en/brokers/api but not only I can only get an Metatrader **5** API key but I also need to have a company and request access to API as if I was a broker.

Is there any other way to make transactions from the server on my personal account?

const mt4 = new MetaTrader4({
	apiKey: "CHANGEME",
	reqUrl: "tcp://127.0.0.1:5555",
	pullUrl: "tcp://127.0.0.1:5556"
});

**Comment by peterszombati** [comment]
Hi! @Edduard 

In the https://github.com/peterszombati/metatrader4/blob/master/README.md
you can found a step-by-step guide how it will works,
api key just have to match with: https://raw.githubusercontent.com/peterszombati/metatrader4/master/src/MetaTrader4Bridge.mq4
in this file with full text search "extern string APIKEY"

You have to running an expert on your mt4 and this nodejs script will connect to this expert

**Comment by Edduard** [comment]
Hi, 

Thank you for the answer. My question was more about where can I get the API key myself? Now I know where to replace it in code but how do I get the actual API key from Metatrader? Should I have a business account? Should I become a broker in order to have access to the API key?

I know it's not a question directly related to the repository but I don't know anyone else to ask this question. And since you made it work I'm asking you.

Thank you
