### ISSUE TITLE
[feature] support zeromq.js version 6

### ISSUE THREAD

**Issue by dawadam** [peterszombati/metatrader4#8]
The new version 6 of zeromq.js provides solutions to many fundamental problems.

**Comment by peterszombati** [comment]
published in npm

**Comment by peterszombati** [comment]
can you check all good ?

**Comment by dawadam** [comment]
Thanks for the quick update.
The build is not in the dependency.

Folder `/node_modules/metatrader4/build` does not exist.

**Comment by peterszombati** [comment]
fix done

**Comment by dawadam** [comment]
Ok, the import works.
But my sample code doesn't.
I will investigate.

**Comment by dawadam** [comment]
Ok, I made a mistake removing "monitor()"

**Comment by dawadam** [comment]
Great
1.0.5 works
Thanks
